### ISSUE TITLE
nxtjs_deployError- useSearchParams() should be wrapped in a suspense boundary at page "/pageWillsManager".- branch-devWagmiImplementaiton-WillSettler_Vercel 

### ISSUE THREAD

**Issue by BlockchainDeveloper009** [BlockchainDeveloper009/defi_jul2_sol_hd_ts#1]
[read-here-toofix](https://nextjs.org/docs/messages/missing-suspense-with-csr-bailout)
```
<html>
<body>
<!--StartFragment-->
Ex-10: GetWillsByUsers - TypeError: Cannot read properties of undefined (reading 'length')
--
13:49:27.437 | ⨯ useSearchParams() should be wrapped in a suspense boundary at page "/pageWillsManager". Read more: https://nextjs.org/docs/messages/missing-suspense-with-csr-bailout
13:49:27.437 | at n (/vercel/path0/.next/server/chunks/4867.js:24:94839)
13:49:27.437 | at h (/vercel/path0/.next/server/chunks/4867.js:24:106632)
13:49:27.437 | at ed (/vercel/path0/.next/server/app/pageWillsManager/page.js:1:39883)
13:49:27.438 | at nM (/vercel/path0/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:47419)

<!--EndFragment-->
</body>
</html>
```

**Comment by BlockchainDeveloper009** [comment]
> [read-here-toofix](https://nextjs.org/docs/messages/missing-suspense-with-csr-bailout)
> 
> ```
> <html>
> <body>
> 
> Ex-10: GetWillsByUsers - TypeError: Cannot read properties of undefined (reading 'length')
> --
> 13:49:27.437 | ⨯ useSearchParams() should be wrapped in a suspense boundary at page "/pageWillsManager". Read more: https://nextjs.org/docs/messages/missing-suspense-with-csr-bailout
> 13:49:27.437 | at n (/vercel/path0/.next/server/chunks/4867.js:24:94839)
> 13:49:27.437 | at h (/vercel/path0/.next/server/chunks/4867.js:24:106632)
> 13:49:27.437 | at ed (/vercel/path0/.next/server/app/pageWillsManager/page.js:1:39883)
> 13:49:27.438 | at nM (/vercel/path0/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:47419)
> 
> 
> </body>
> </html>
> ```
Errors occurs in below pages
["/pageWillsManager"](/pageWillsManager)
["/pageWillsManagerCancel"](/pageWillsManagerCancel)
["/pageWillsManagerEdit"](/pageWillsManagerEdit)
